apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-db
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: wordpress-db
        image: mysql
        ports:
        - containerPort: 3306
          name: wordpress-db
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef: 
                name: mysql-secret
                key:    mysql_root_password
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef: 
                name: mysql-secret
                key:    mysql_user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef: 
                name: mysql-secret
                key:    mysql_password             
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef: 
                name: mysql-configmap
                key: mysql_db
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    app: mysql
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: db-service
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi