apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-app
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: words
        image: wordpress:apache
        ports:
        - containerPort: 8080
          name: api
        env:
          - name:  WORDPRESS_DB_HOST
            valueFrom:
              configMapKeyRef: 
                name: mysql-configmap
                key:  database_url
          - name: WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef: 
                name: mysql-secret
                key:    mysql_user
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef: 
                name: mysql-secret
                key:    mysql_password             
          - name: WORDPRESS_DB_NAME
            valueFrom:
              configMapKeyRef: 
                name: mysql-configmap
                key: mysql_db
        volumeMounts:
          - name: wordpress-persistent-storage
            mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: wordpress
spec:
  ports:
    - port: 8081
      targetPort: 80
      nodePort: 30060
      name: wordpress-service
  selector:
    app: wordpress
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi